In [6]:
import os

base = "/kaggle/input"

for root, dirs, files in os.walk(base):
    level = root.replace(base, "").count(os.sep)

    if level <= 3:
        indent = "  " * level
        print(f"{indent}{os.path.basename(root)}/")

        for f in files[:10]:
            print(f"{indent}  {f}")

input/
  datasets/
    rasangabawanthi/
      mindbridge-daisee/

In [7]:
import os

base = "/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee"

for root, dirs, files in os.walk(base):
    level = root.replace(base, "").count(os.sep)

    if level <= 2:
        indent = "  " * level
        print(f"{indent}{os.path.basename(root)}/")

        for f in files[:15]:
            print(f"{indent}  {f}")

mindbridge-daisee/
  DAiSEE/
    README.txt
    hog.py
    extractFrames.py
    Labels/
      TrainLabels.csv
      AllLabels.csv
      TestLabels.csv
      ValidationLabels.csv
    DataSet/
      Test.txt
      Validation.txt
      Train.txt
    GenderClips/
      Females
      Males

In [8]:
import pandas as pd

label_path = "/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/Labels/TrainLabels.csv"

train_labels = pd.read_csv(label_path)

print("Shape:", train_labels.shape)
print("\nColumns:")
print(train_labels.columns.tolist())

train_labels.head(10)

Shape: (5358, 5)

Columns:
['ClipID', 'Boredom', 'Engagement', 'Confusion', 'Frustration ']

           ClipID  Boredom  Engagement  Confusion  Frustration
0  1100011002.avi        0           2          0             0
1  1100011003.avi        0           2          0             0
2  1100011004.avi        0           3          0             0
3  1100011005.avi        0           3          0             0
4  1100011006.avi        0           3          0             0
5  1100011007.avi        1           2          0             0
6  1100011008.avi        0           3          0             0
7  1100011009.avi        0           2          1             0
8  1100011010.avi        0           3          0             0
9  1100011011.avi        0           3          0             0

In [9]:
print(train_labels.describe())

print("\nValue counts:")
for col in train_labels.columns:
    if col != train_labels.columns[0]:
        print(f"\n--- {col} ---")
        print(train_labels[col].value_counts().sort_index())

           Boredom   Engagement    Confusion  Frustration
count  5358.000000  5358.000000  5358.000000   5358.000000
mean      0.804405     2.413027     0.430198      0.270997
std       0.855973     0.600070     0.692825      0.563085
min       0.000000     0.000000     0.000000      0.000000
25%       0.000000     2.000000     0.000000      0.000000
50%       1.000000     2.000000     0.000000      0.000000
75%       1.000000     3.000000     1.000000      0.000000
max       3.000000     3.000000     3.000000      3.000000

Value counts:

--- Boredom ---
Boredom
0    2433
1    1696
2    1073
3     156
Name: count, dtype: int64

--- Engagement ---
Engagement
0      34
1     213
2    2617
3    2494
Name: count, dtype: int64

--- Confusion ---
Confusion
0    3616
1    1245
2     431
3      66
Name: count, dtype: int64

--- Frustration  ---
Frustration
0    4183
1     941
2     191
3      43
Name: count, dtype: int64

In [10]:
# Clean column names
train_labels.columns = train_labels.columns.str.strip()

print(train_labels.columns.tolist())

['ClipID', 'Boredom', 'Engagement', 'Confusion', 'Frustration']

In [11]:
train_labels['confused_label'] = (
    train_labels['Confusion'] >= 1
).astype(int)

print(train_labels['confused_label'].value_counts())

print("\nPercentage:")
print(
    train_labels['confused_label']
    .value_counts(normalize=True) * 100
)

confused_label
0    3616
1    1742
Name: count, dtype: int64

Percentage:
confused_label
0    67.487869
1    32.512131
Name: proportion, dtype: float64

In [12]:
base_labels = "/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/Labels"

val_labels = pd.read_csv(
    f"{base_labels}/ValidationLabels.csv"
)

test_labels = pd.read_csv(
    f"{base_labels}/TestLabels.csv"
)

# Clean column names
val_labels.columns = val_labels.columns.str.strip()
test_labels.columns = test_labels.columns.str.strip()

# Create same binary target
val_labels['confused_label'] = (
    val_labels['Confusion'] >= 1
).astype(int)

test_labels['confused_label'] = (
    test_labels['Confusion'] >= 1
).astype(int)

print("TRAIN")
print(train_labels['confused_label'].value_counts())

print("\nVALIDATION")
print(val_labels['confused_label'].value_counts())

print("\nTEST")
print(test_labels['confused_label'].value_counts())

TRAIN
confused_label
0    3616
1    1742
Name: count, dtype: int64

VALIDATION
confused_label
0    942
1    487
Name: count, dtype: int64

TEST
confused_label
0    1200
1     584
Name: count, dtype: int64

In [13]:
print(train_labels[['ClipID', 'Confusion', 'confused_label']].head(20))

            ClipID  Confusion  confused_label
0   1100011002.avi          0               0
1   1100011003.avi          0               0
2   1100011004.avi          0               0
3   1100011005.avi          0               0
4   1100011006.avi          0               0
5   1100011007.avi          0               0
6   1100011008.avi          0               0
7   1100011009.avi          1               1
8   1100011010.avi          0               0
9   1100011011.avi          0               0
10  1100011012.avi          2               1
11  1100011013.avi          0               0
12  1100011014.avi          0               0
13  1100011015.avi          0               0
14  1100011016.avi          0               0
15  1100011017.avi          0               0
16  1100011018.avi          0               0
17  1100011019.avi          0               0
18  1100011020.avi          0               0
19  1100011021.avi          0               0

In [14]:
import os

dataset_root = "/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE"

video_files = []

for root, dirs, files in os.walk(dataset_root):
    for file in files:
        if file.lower().endswith((".avi", ".mp4", ".mov", ".mkv")):
            video_files.append(os.path.join(root, file))

print("Total video files found:", len(video_files))

print("\nFirst 20 video paths:")
for path in video_files[:20]:
    print(path)

Total video files found: 9068

First 20 video paths:
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231047/4000231047.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231001/4000231001.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231049/4000231049.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232035/4000232035.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232044/4000232044.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232042/4000232042.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232059/4000232059.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231033/4000231033.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231034/4000231034.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232004/4000232004.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232037/4000232037.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231071/4000231071.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232072/4000232072.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232018/4000232018.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231008/4000231008.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232016/4000232016.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231073/4000231073.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231061/4000231061.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000232054/4000232054.avi
/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Validation/400023/4000231013/4000231013.avi

In [15]:
import os

video_lookup = {
    os.path.basename(path): path
    for path in video_files
}

matched = train_labels['ClipID'].isin(video_lookup.keys())

print("Train label clips:", len(train_labels))
print("Matched video clips:", matched.sum())
print("Missing video clips:", (~matched).sum())

Train label clips: 5358
Matched video clips: 5358
Missing video clips: 0

In [16]:
import cv2
import os

# First training clip
first_clip = train_labels.iloc[0]['ClipID']
first_video_path = video_lookup[first_clip]

print("ClipID:", first_clip)
print("Video path:", first_video_path)

cap = cv2.VideoCapture(first_video_path)

fps = cap.get(cv2.CAP_PROP_FPS)
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

duration = frame_count / fps if fps > 0 else 0

print("\nFPS:", fps)
print("Frames:", frame_count)
print("Resolution:", width, "x", height)
print("Duration:", round(duration, 2), "seconds")

cap.release()

ClipID: 1100011002.avi
Video path: /kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/DataSet/Train/110001/1100011002/1100011002.avi

FPS: 30.0
Frames: 300
Resolution: 640 x 480
Duration: 10.0 seconds

In [17]:
import cv2

print("OpenCV version:", cv2.__version__)

try:
    import mediapipe as mp
    print("MediaPipe version:", mp.__version__)
    print("MediaPipe imported successfully!")
except Exception as e:
    print("MediaPipe error:", e)

OpenCV version: 4.14.0
MediaPipe error: No module named 'mediapipe'

In [18]:
import sys

!{sys.executable} -m pip install -q mediapipe

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.9/37.9 MB 47.4 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.4/137.4 kB 5.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.

In [19]:
!pip install mediapipe

Requirement already satisfied: mediapipe in /usr/local/lib/python3.13/dist-packages (1.0.1)
Requirement already satisfied: absl-py~=2.3 in /usr/local/lib/python3.13/dist-packages (from mediapipe) (2.5.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from mediapipe) (2026.7.22)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from mediapipe) (2.1.3)
Requirement already satisfied: sounddevice~=0.5 in /usr/local/lib/python3.13/dist-packages (from mediapipe) (0.5.6)
Requirement already satisfied: flatbuffers~=25.9 in /usr/local/lib/python3.13/dist-packages (from mediapipe) (25.12.19)
Requirement already satisfied: opencv-contrib-python in /usr/local/lib/python3.13/dist-packages (from mediapipe) (4.14.0.94)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from mediapipe) (3.10.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.13/dist-packages (from sounddevice~=0.5->mediapipe) (2.1.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->mediapipe) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->mediapipe) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->mediapipe) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->mediapipe) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->mediapipe) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->mediapipe) (12.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->mediapipe) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib->mediapipe) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.17.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi->sounddevice~=0.5->mediapipe) (3.0)

In [20]:
import mediapipe as mp
import cv2

print("MediaPipe version:", mp.__version__)
print("OpenCV version:", cv2.__version__)
print("MediaPipe imported successfully!")

MediaPipe version: 1.0.1
OpenCV version: 4.14.0
MediaPipe imported successfully!

In [21]:
import mediapipe as mp

print("Has mp.solutions:", hasattr(mp, "solutions"))

Has mp.solutions: False

In [22]:
!wget -q -O /kaggle/working/face_landmarker.task \
https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/latest/face_landmarker.task

print("Model downloaded")

Model downloaded

In [23]:
import mediapipe as mp

BaseOptions = mp.tasks.BaseOptions
FaceLandmarker = mp.tasks.vision.FaceLandmarker
FaceLandmarkerOptions = mp.tasks.vision.FaceLandmarkerOptions
VisionRunningMode = mp.tasks.vision.RunningMode

print("MediaPipe Tasks FaceLandmarker ready!")

MediaPipe Tasks FaceLandmarker ready!

In [24]:
import cv2
import mediapipe as mp
import matplotlib.pyplot as plt
import os
import pandas as pd

# Rebuild labels and video lookup if session restarted
label_path = "/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE/Labels/TrainLabels.csv"

train_labels = pd.read_csv(label_path)
train_labels.columns = train_labels.columns.str.strip()

dataset_root = "/kaggle/input/datasets/rasangabawanthi/mindbridge-daisee/DAiSEE"

video_files = []

for root, dirs, files in os.walk(dataset_root):
    for file in files:
        if file.lower().endswith((".avi", ".mp4", ".mov", ".mkv")):
            video_files.append(os.path.join(root, file))

video_lookup = {
    os.path.basename(path): path
    for path in video_files
}

first_clip = train_labels.iloc[0]["ClipID"]
first_video_path = video_lookup[first_clip]

# Read middle frame
cap = cv2.VideoCapture(first_video_path)

frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
cap.set(cv2.CAP_PROP_POS_FRAMES, frame_count // 2)

success, frame = cap.read()
cap.release()

if not success:
    print("Could not read frame")

else:
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    mp_image = mp.Image(
        image_format=mp.ImageFormat.SRGB,
        data=rgb
    )

    options = FaceLandmarkerOptions(
        base_options=BaseOptions(
            model_asset_path="/kaggle/working/face_landmarker.task"
        ),
        running_mode=VisionRunningMode.IMAGE,
        num_faces=1,
        min_face_detection_confidence=0.5,
        min_face_presence_confidence=0.5
    )

    with FaceLandmarker.create_from_options(options) as landmarker:
        result = landmarker.detect(mp_image)

    if result.face_landmarks:
        landmarks = result.face_landmarks[0]

        print("Face detected ✅")
        print("Number of landmarks:", len(landmarks))
    else:
        print("No face detected ❌")

    plt.figure(figsize=(7,5))
    plt.imshow(rgb)
    plt.axis("off")
    plt.title(first_clip)
    plt.show()

WARNING: Logging before InitGoogle() is written to STDERR
W0000 00:00:1791300234.650614     197 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1791300234.672447     202 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791300234.697513     202 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

Face detected ✅
Number of landmarks: 478

In [25]:
import numpy as np

# -----------------------------------------
# Helper function
# -----------------------------------------
def point_distance(p1, p2):
    return np.sqrt(
        (p1.x - p2.x) ** 2 +
        (p1.y - p2.y) ** 2
    )

# -----------------------------------------
# Eye Aspect Ratio style openness
# -----------------------------------------
def calculate_eye_openness(landmarks, eye_indices):
    p1 = landmarks[eye_indices[0]]
    p2 = landmarks[eye_indices[1]]
    p3 = landmarks[eye_indices[2]]
    p4 = landmarks[eye_indices[3]]
    p5 = landmarks[eye_indices[4]]
    p6 = landmarks[eye_indices[5]]

    # Two vertical eye distances
    vertical_1 = point_distance(p2, p6)
    vertical_2 = point_distance(p3, p5)

    # Horizontal eye width
    horizontal = point_distance(p1, p4)

    if horizontal == 0:
        return 0.0

    openness = (
        vertical_1 + vertical_2
    ) / (2.0 * horizontal)

    return openness


# MediaPipe eye landmark indices
LEFT_EYE = [33, 160, 158, 133, 153, 144]
RIGHT_EYE = [362, 385, 387, 263, 373, 380]

if result.face_landmarks:

    landmarks = result.face_landmarks[0]

    left_eye_openness = calculate_eye_openness(
        landmarks,
        LEFT_EYE
    )

    right_eye_openness = calculate_eye_openness(
        landmarks,
        RIGHT_EYE
    )

    mean_eye_openness = (
        left_eye_openness +
        right_eye_openness
    ) / 2

    print(
        "Left eye openness:",
        round(left_eye_openness, 4)
    )

    print(
        "Right eye openness:",
        round(right_eye_openness, 4)
    )

    print(
        "Mean eye openness:",
        round(mean_eye_openness, 4)
    )

else:
    print("No face landmarks available.")

Left eye openness: 0.3455
Right eye openness: 0.3961
Mean eye openness: 0.3708

In [26]:
import cv2
import numpy as np

def estimate_head_pose(frame, landmarks):
    h, w = frame.shape[:2]

    # 2D facial landmark points from MediaPipe
    image_points = np.array([
        [landmarks[1].x * w,   landmarks[1].y * h],    # Nose tip
        [landmarks[152].x * w, landmarks[152].y * h],  # Chin
        [landmarks[33].x * w,  landmarks[33].y * h],   # Left eye outer corner
        [landmarks[263].x * w, landmarks[263].y * h],  # Right eye outer corner
        [landmarks[61].x * w,  landmarks[61].y * h],   # Left mouth corner
        [landmarks[291].x * w, landmarks[291].y * h],  # Right mouth corner
    ], dtype=np.float64)

    # Approximate generic 3D face model
    model_points = np.array([
        [0.0,    0.0,    0.0],      # Nose tip
        [0.0, -330.0,  -65.0],      # Chin
        [-225.0, 170.0, -135.0],    # Left eye
        [225.0, 170.0, -135.0],     # Right eye
        [-150.0, -150.0, -125.0],   # Left mouth
        [150.0, -150.0, -125.0],    # Right mouth
    ])

    focal_length = w

    camera_matrix = np.array([
        [focal_length, 0, w / 2],
        [0, focal_length, h / 2],
        [0, 0, 1]
    ], dtype=np.float64)

    distortion = np.zeros((4, 1))

    success, rotation_vector, translation_vector = cv2.solvePnP(
        model_points,
        image_points,
        camera_matrix,
        distortion,
        flags=cv2.SOLVEPNP_ITERATIVE
    )

    if not success:
        return None

    rotation_matrix, _ = cv2.Rodrigues(rotation_vector)

    angles, _, _, _, _, _ = cv2.RQDecomp3x3(rotation_matrix)

    pitch = angles[0]
    yaw   = angles[1]
    roll  = angles[2]

    return pitch, yaw, roll

In [27]:
if result.face_landmarks:

    landmarks = result.face_landmarks[0]

    pose = estimate_head_pose(frame, landmarks)

    if pose is not None:
        pitch, yaw, roll = pose

        print("Head Pitch:", round(pitch, 2))
        print("Head Yaw:", round(yaw, 2))
        print("Head Roll:", round(roll, 2))

    else:
        print("Head pose estimation failed.")

else:
    print("No face detected.")

Head Pitch: 166.28
Head Yaw: 9.47
Head Roll: -2.38

In [32]:
def normalize_pitch(pitch):
    if pitch > 90:
        pitch = 180 - pitch
    elif pitch < -90:
        pitch = -180 - pitch

    return pitch

In [33]:
if result.face_landmarks:

    landmarks = result.face_landmarks[0]

    pose = estimate_head_pose(frame, landmarks)

    if pose is not None:
        pitch, yaw, roll = pose

        pitch = normalize_pitch(pitch)

        print("Normalized Head Pitch:", round(pitch, 2))
        print("Head Yaw:", round(yaw, 2))
        print("Head Roll:", round(roll, 2))

Normalized Head Pitch: 13.72
Head Yaw: 9.47
Head Roll: -2.38

In [34]:
import numpy as np

def mean_point(landmarks, indices):
    xs = [landmarks[i].x for i in indices]
    ys = [landmarks[i].y for i in indices]

    return np.mean(xs), np.mean(ys)


def calculate_gaze_ratio(landmarks):

    # Iris landmarks
    LEFT_IRIS = [468, 469, 470, 471, 472]
    RIGHT_IRIS = [473, 474, 475, 476, 477]

    # Eye outer/inner corners
    LEFT_CORNERS = [33, 133]
    RIGHT_CORNERS = [362, 263]

    left_iris_x, _ = mean_point(
        landmarks,
        LEFT_IRIS
    )

    right_iris_x, _ = mean_point(
        landmarks,
        RIGHT_IRIS
    )

    left_x1 = landmarks[LEFT_CORNERS[0]].x
    left_x2 = landmarks[LEFT_CORNERS[1]].x

    right_x1 = landmarks[RIGHT_CORNERS[0]].x
    right_x2 = landmarks[RIGHT_CORNERS[1]].x

    # Normalize iris location inside each eye
    left_min = min(left_x1, left_x2)
    left_max = max(left_x1, left_x2)

    right_min = min(right_x1, right_x2)
    right_max = max(right_x1, right_x2)

    left_ratio = (
        (left_iris_x - left_min) /
        (left_max - left_min + 1e-6)
    )

    right_ratio = (
        (right_iris_x - right_min) /
        (right_max - right_min + 1e-6)
    )

    mean_ratio = (
        left_ratio + right_ratio
    ) / 2

    return left_ratio, right_ratio, mean_ratio

In [35]:
if result.face_landmarks:

    landmarks = result.face_landmarks[0]

    left_gaze, right_gaze, mean_gaze = calculate_gaze_ratio(
        landmarks
    )

    print("Left gaze ratio:", round(left_gaze, 4))
    print("Right gaze ratio:", round(right_gaze, 4))
    print("Mean gaze ratio:", round(mean_gaze, 4))

Left gaze ratio: 0.452
Right gaze ratio: 0.5056
Mean gaze ratio: 0.4788

In [36]:
import cv2
import numpy as np
import mediapipe as mp

def calculate_face_visibility(video_path, samples=30):

    cap = cv2.VideoCapture(video_path)

    total_frames = int(
        cap.get(cv2.CAP_PROP_FRAME_COUNT)
    )

    if total_frames <= 0:
        cap.release()
        return 0.0, 0, 0

    frame_indices = np.linspace(
        0,
        total_frames - 1,
        samples
    ).astype(int)

    detected = 0
    processed = 0

    options = FaceLandmarkerOptions(
        base_options=BaseOptions(
            model_asset_path="/kaggle/working/face_landmarker.task"
        ),
        running_mode=VisionRunningMode.IMAGE,
        num_faces=1,
        min_face_detection_confidence=0.5,
        min_face_presence_confidence=0.5
    )

    with FaceLandmarker.create_from_options(options) as landmarker:

        for idx in frame_indices:

            cap.set(
                cv2.CAP_PROP_POS_FRAMES,
                int(idx)
            )

            success, frame = cap.read()

            if not success:
                continue

            processed += 1

            rgb = cv2.cvtColor(
                frame,
                cv2.COLOR_BGR2RGB
            )

            mp_image = mp.Image(
                image_format=mp.ImageFormat.SRGB,
                data=rgb
            )

            detection = landmarker.detect(mp_image)

            if detection.face_landmarks:
                detected += 1

    cap.release()

    visibility_ratio = (
        detected / processed
        if processed > 0 else 0
    )

    return visibility_ratio, detected, processed

In [37]:
visibility, detected, processed = calculate_face_visibility(
    first_video_path,
    samples=30
)

print("Frames processed:", processed)
print("Face detected frames:", detected)
print(
    "Face visibility ratio:",
    round(visibility, 4)
)

W0000 00:00:1791300817.286168     226 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791300817.295872     229 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791300817.318837     230 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

Frames processed: 30
Face detected frames: 30
Face visibility ratio: 1.0

In [42]:
import cv2
import numpy as np
import mediapipe as mp


def extract_clip_features(video_path, samples=30):

    cap = cv2.VideoCapture(video_path)

    total_frames = int(
        cap.get(cv2.CAP_PROP_FRAME_COUNT)
    )

    if total_frames <= 0:
        cap.release()
        return None

    frame_indices = np.linspace(
        0,
        total_frames - 1,
        samples
    ).astype(int)

    eye_values = []
    gaze_values = []

    pitch_values = []
    yaw_values = []
    roll_values = []

    processed_frames = 0
    face_detected_frames = 0

    options = FaceLandmarkerOptions(
        base_options=BaseOptions(
            model_asset_path="/kaggle/working/face_landmarker.task"
        ),
        running_mode=VisionRunningMode.IMAGE,
        num_faces=1,
        min_face_detection_confidence=0.5,
        min_face_presence_confidence=0.5
    )

    with FaceLandmarker.create_from_options(options) as landmarker:

        for frame_index in frame_indices:

            cap.set(
                cv2.CAP_PROP_POS_FRAMES,
                int(frame_index)
            )

            success, frame = cap.read()

            if not success:
                continue

            processed_frames += 1

            rgb = cv2.cvtColor(
                frame,
                cv2.COLOR_BGR2RGB
            )

            mp_image = mp.Image(
                image_format=mp.ImageFormat.SRGB,
                data=rgb
            )

            result_frame = landmarker.detect(mp_image)

            if not result_frame.face_landmarks:
                continue

            face_detected_frames += 1

            landmarks = result_frame.face_landmarks[0]

            # -----------------------------
            # Eye openness
            # -----------------------------

            left_eye = calculate_eye_openness(
                landmarks,
                LEFT_EYE
            )

            right_eye = calculate_eye_openness(
                landmarks,
                RIGHT_EYE
            )

            mean_eye = (
                left_eye + right_eye
            ) / 2

            eye_values.append(mean_eye)

            # -----------------------------
            # Gaze proxy
            # -----------------------------

            _, _, mean_gaze = calculate_gaze_ratio(
                landmarks
            )

            gaze_values.append(mean_gaze)

            # -----------------------------
            # Head pose
            # -----------------------------

            pose = estimate_head_pose(
                frame,
                landmarks
            )

            if pose is not None:

                pitch, yaw, roll = pose

                pitch = normalize_pitch(pitch)

                pitch_values.append(pitch)
                yaw_values.append(yaw)
                roll_values.append(roll)

    cap.release()

    if processed_frames == 0:
        return None

    face_visibility_ratio = (
        face_detected_frames /
        processed_frames
    )

    def safe_mean(values):
        arr = np.asarray(values, dtype=float)
    
        if arr.size == 0:
            return np.nan
    
        return float(np.mean(arr))


    def safe_std(values):
        arr = np.asarray(values, dtype=float)
    
        if arr.size == 0:
            return np.nan
    
        return float(np.std(arr))

    return {

        "mean_eye_openness":
            safe_mean(eye_values),

        "std_eye_openness":
            safe_std(eye_values),

        "mean_gaze_ratio":
            safe_mean(gaze_values),

        "std_gaze_ratio":
            safe_std(gaze_values),

        "mean_pitch":
            safe_mean(pitch_values),

        "mean_yaw":
            safe_mean(yaw_values),

        "mean_roll":
            safe_mean(roll_values),

        "mean_abs_pitch":
            safe_mean(np.abs(pitch_values)),

        "mean_abs_yaw":
            safe_mean(np.abs(yaw_values)),

        "mean_abs_roll":
            safe_mean(np.abs(roll_values)),

        "face_visibility_ratio":
            face_visibility_ratio,

        "processed_frames":
            processed_frames,

        "face_detected_frames":
            face_detected_frames
    }

In [43]:
sample_features = extract_clip_features(
    first_video_path,
    samples=30
)

sample_features

W0000 00:00:1791301236.990366     270 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301236.998022     273 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301237.014018     272 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

{'mean_eye_openness': 0.3427173356234073,
 'std_eye_openness': 0.08159134786387622,
 'mean_gaze_ratio': 0.4779166682504924,
 'std_gaze_ratio': 0.016080833980929125,
 'mean_pitch': 12.994087517165234,
 'mean_yaw': 3.0720655806759445,
 'mean_roll': 1.7608009629598576,
 'mean_abs_pitch': 12.994087517165234,
 'mean_abs_yaw': 6.0439941610373795,
 'mean_abs_roll': 5.137476190680882,
 'face_visibility_ratio': 1.0,
 'processed_frames': 30,
 'face_detected_frames': 30}

In [44]:
import pandas as pd
import numpy as np

feature_rows = []

sample_labels = train_labels.head(50)

for i, row in sample_labels.iterrows():

    clip_id = row['ClipID']

    try:
        video_path = video_lookup[clip_id]

        features = extract_clip_features(
            video_path,
            samples=30
        )

        if features is None:
            print(f"{clip_id}: feature extraction failed")
            continue

        features['ClipID'] = clip_id
        features['Confusion'] = row['Confusion']
        features['confused_label'] = row['confused_label']

        feature_rows.append(features)

        print(
            f"{len(feature_rows)}/50 completed - {clip_id}"
        )

    except Exception as e:
        print(
            f"ERROR - {clip_id}: {e}"
        )

visual_sample_df = pd.DataFrame(feature_rows)

print("\nFinished!")
print("Shape:", visual_sample_df.shape)

visual_sample_df.head()

W0000 00:00:1791301394.083125     285 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301394.091664     288 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301394.117380     288 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011002.avi: 'confused_label'

W0000 00:00:1791301395.119797     298 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301395.126902     300 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301395.141927     300 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011003.avi: 'confused_label'

W0000 00:00:1791301396.136689     311 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301396.143652     314 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301396.164510     314 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011004.avi: 'confused_label'

W0000 00:00:1791301397.125179     324 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301397.132348     327 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301397.147898     326 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011005.avi: 'confused_label'

W0000 00:00:1791301398.158047     337 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301398.165249     340 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301398.184993     341 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011006.avi: 'confused_label'

W0000 00:00:1791301399.140836     350 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301399.148141     353 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301399.170674     354 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011007.avi: 'confused_label'

W0000 00:00:1791301400.196046     363 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301400.203165     365 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301400.226178     365 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011008.avi: 'confused_label'

W0000 00:00:1791301401.143039     376 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301401.150092     379 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301401.174081     379 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011009.avi: 'confused_label'

W0000 00:00:1791301402.158679     389 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301402.165648     391 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301402.188674     391 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011010.avi: 'confused_label'

W0000 00:00:1791301403.176912     402 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301403.184068     405 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301403.207836     405 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011011.avi: 'confused_label'

W0000 00:00:1791301404.164969     415 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301404.173173     418 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301404.195221     419 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011012.avi: 'confused_label'

W0000 00:00:1791301405.183037     428 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301405.190220     430 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301405.212977     432 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011013.avi: 'confused_label'

W0000 00:00:1791301406.205488     441 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301406.212300     443 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301406.227866     443 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011014.avi: 'confused_label'

W0000 00:00:1791301407.225004     454 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301407.232148     456 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301407.254619     456 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011015.avi: 'confused_label'

W0000 00:00:1791301408.252572     467 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301408.259410     469 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301408.278872     471 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011016.avi: 'confused_label'

W0000 00:00:1791301409.274419     480 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301409.281568     482 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301409.301660     484 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011017.avi: 'confused_label'

W0000 00:00:1791301410.305323     493 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301410.312274     496 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301410.327508     496 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011018.avi: 'confused_label'

W0000 00:00:1791301411.312448     506 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301411.319928     509 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301411.340861     510 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011019.avi: 'confused_label'

W0000 00:00:1791301412.332165     519 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301412.339064     521 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301412.354612     522 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011020.avi: 'confused_label'

W0000 00:00:1791301413.298363     532 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301413.305364     534 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301413.324343     536 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011021.avi: 'confused_label'

W0000 00:00:1791301414.284426     545 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301414.292172     547 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301414.307873     549 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011022.avi: 'confused_label'

W0000 00:00:1791301415.299596     558 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301415.306421     560 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301415.328749     560 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011023.avi: 'confused_label'

W0000 00:00:1791301416.321146     571 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301416.328076     574 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301416.347190     575 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011025.avi: 'confused_label'

W0000 00:00:1791301417.345053     584 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301417.351919     586 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301417.367770     586 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011026.avi: 'confused_label'

W0000 00:00:1791301418.357549     597 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301418.364584     600 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301418.386556     599 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011027.avi: 'confused_label'

W0000 00:00:1791301419.372985     610 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301419.380602     612 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301419.396273     614 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011028.avi: 'confused_label'

W0000 00:00:1791301420.380507     623 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301420.387603     625 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301420.406446     627 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011029.avi: 'confused_label'

W0000 00:00:1791301421.357730     636 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301421.365752     638 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301421.389259     638 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011031.avi: 'confused_label'

W0000 00:00:1791301422.376571     649 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301422.383448     651 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301422.404903     652 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011032.avi: 'confused_label'

W0000 00:00:1791301423.965830     662 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301423.972752     664 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301423.988530     666 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011034.avi: 'confused_label'

W0000 00:00:1791301425.495730     675 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301425.502580     677 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301425.521123     679 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011035.avi: 'confused_label'

W0000 00:00:1791301427.028901     688 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301427.035626     690 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301427.050529     690 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011037.avi: 'confused_label'

W0000 00:00:1791301428.606581     701 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301428.613409     704 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301428.628977     704 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011038.avi: 'confused_label'

W0000 00:00:1791301430.787469     714 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301430.795324     716 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301430.811037     718 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011040.avi: 'confused_label'

W0000 00:00:1791301432.339871     727 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301432.346888     730 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301432.362012     731 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011046.avi: 'confused_label'

W0000 00:00:1791301433.895554     740 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301433.903759     743 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301433.919493     742 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011047.avi: 'confused_label'

W0000 00:00:1791301434.873386     753 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301434.880265     756 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301434.895947     756 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011048.avi: 'confused_label'

W0000 00:00:1791301435.947404     766 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301435.954649     769 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301435.969565     769 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011049.avi: 'confused_label'

W0000 00:00:1791301436.920282     779 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301436.927317     782 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301436.942771     783 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011050.avi: 'confused_label'

W0000 00:00:1791301437.891019     792 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301437.898672     794 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301437.914577     796 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011051.avi: 'confused_label'

W0000 00:00:1791301438.871943     805 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301438.878956     808 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301438.894605     809 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011052.avi: 'confused_label'

W0000 00:00:1791301439.849607     818 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301439.856465     820 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301439.871636     820 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011053.avi: 'confused_label'

W0000 00:00:1791301440.883891     831 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301440.890566     834 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301440.906168     834 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011054.avi: 'confused_label'

W0000 00:00:1791301441.855077     844 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301441.862226     847 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301441.877574     847 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011055.avi: 'confused_label'

W0000 00:00:1791301442.920322     857 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301442.927132     860 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301442.942579     859 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011056.avi: 'confused_label'

W0000 00:00:1791301443.931243     870 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301443.938027     872 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301443.953566     874 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011057.avi: 'confused_label'

W0000 00:00:1791301444.926250     883 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301444.933078     886 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301444.948614     885 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011058.avi: 'confused_label'

W0000 00:00:1791301445.901954     896 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301445.908715     898 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301445.924241     900 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011059.avi: 'confused_label'

W0000 00:00:1791301446.860906     909 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301446.867556     911 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301446.882633     911 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011060.avi: 'confused_label'

W0000 00:00:1791301447.887937     922 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301447.894866     925 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301447.910725     926 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

ERROR - 1100011062.avi: 'confused_label'

Finished!
Shape: (0, 0)

Empty DataFrame
Columns: []
Index: []

In [45]:
# Clean column names first
train_labels.columns = train_labels.columns.str.strip()

# Re-create binary confusion label
train_labels['confused_label'] = (
    train_labels['Confusion'] >= 1
).astype(int)

print(train_labels.columns.tolist())

print("\nConfusion label counts:")
print(train_labels['confused_label'].value_counts())

['ClipID', 'Boredom', 'Engagement', 'Confusion', 'Frustration', 'confused_label']

Confusion label counts:
confused_label
0    3616
1    1742
Name: count, dtype: int64

In [46]:
train_labels[
    ['ClipID', 'Confusion', 'confused_label']
].head()

           ClipID  Confusion  confused_label
0  1100011002.avi          0               0
1  1100011003.avi          0               0
2  1100011004.avi          0               0
3  1100011005.avi          0               0
4  1100011006.avi          0               0

In [47]:
feature_rows = []

sample_labels = train_labels.head(50)

for i, row in sample_labels.iterrows():

    clip_id = row['ClipID']

    try:
        video_path = video_lookup[clip_id]

        features = extract_clip_features(
            video_path,
            samples=30
        )

        if features is None:
            print(f"{clip_id}: feature extraction failed")
            continue

        features['ClipID'] = clip_id
        features['Confusion'] = row['Confusion']
        features['confused_label'] = row['confused_label']

        feature_rows.append(features)

        print(
            f"{len(feature_rows)}/50 completed - {clip_id}"
        )

    except Exception as e:
        print(
            f"ERROR - {clip_id}: {e}"
        )

visual_sample_df = pd.DataFrame(feature_rows)

print("\nFinished!")
print("Shape:", visual_sample_df.shape)

visual_sample_df.head()

W0000 00:00:1791301857.495020     943 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301857.502403     946 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301857.520210     947 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

1/50 completed - 1100011002.avi

W0000 00:00:1791301858.492147     956 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301858.499151     959 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301858.514310     959 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

2/50 completed - 1100011003.avi

W0000 00:00:1791301859.956630     969 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301859.963451     971 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301859.978905     973 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

3/50 completed - 1100011004.avi

W0000 00:00:1791301860.990487     982 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301860.997409     984 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301861.016343     986 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

4/50 completed - 1100011005.avi

W0000 00:00:1791301861.924553     995 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301861.931524     998 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301861.949867     999 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

5/50 completed - 1100011006.avi

W0000 00:00:1791301862.893521    1008 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301862.901170    1011 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301862.916716    1012 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

6/50 completed - 1100011007.avi

W0000 00:00:1791301863.875942    1021 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301863.882689    1023 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301863.898623    1024 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

7/50 completed - 1100011008.avi

W0000 00:00:1791301864.793355    1034 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301864.800124    1036 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301864.815586    1038 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

8/50 completed - 1100011009.avi

W0000 00:00:1791301865.743369    1047 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301865.750222    1049 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301865.765549    1049 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

9/50 completed - 1100011010.avi

W0000 00:00:1791301866.659275    1060 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301866.666271    1062 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301866.681563    1062 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

10/50 completed - 1100011011.avi

W0000 00:00:1791301867.656391    1073 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301867.663282    1075 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301867.678601    1077 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

11/50 completed - 1100011012.avi

W0000 00:00:1791301868.573544    1086 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301868.580495    1088 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301868.596259    1090 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

12/50 completed - 1100011013.avi

W0000 00:00:1791301869.531326    1099 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301869.538045    1101 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301869.553427    1103 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

13/50 completed - 1100011014.avi

W0000 00:00:1791301870.532978    1112 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301870.539970    1115 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301870.555351    1116 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

14/50 completed - 1100011015.avi

W0000 00:00:1791301871.510922    1125 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301871.518416    1127 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301871.533744    1129 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

15/50 completed - 1100011016.avi

W0000 00:00:1791301872.506036    1138 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301872.514507    1141 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301872.529855    1140 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

16/50 completed - 1100011017.avi

W0000 00:00:1791301873.478281    1151 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301873.485120    1153 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301873.500694    1155 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

17/50 completed - 1100011018.avi

W0000 00:00:1791301874.454629    1164 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301874.461594    1167 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301874.476768    1167 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

18/50 completed - 1100011019.avi

W0000 00:00:1791301875.418802    1177 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301875.425887    1180 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301875.440969    1180 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

19/50 completed - 1100011020.avi

W0000 00:00:1791301876.421162    1190 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301876.427911    1192 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301876.450441    1192 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

20/50 completed - 1100011021.avi

W0000 00:00:1791301877.431177    1203 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301877.438164    1205 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301877.453550    1205 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

21/50 completed - 1100011022.avi

W0000 00:00:1791301878.489889    1216 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301878.496774    1219 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301878.511884    1219 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

22/50 completed - 1100011023.avi

W0000 00:00:1791301879.487459    1229 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301879.494553    1231 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301879.511865    1233 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

23/50 completed - 1100011025.avi

W0000 00:00:1791301880.480103    1242 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301880.486866    1244 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301880.502544    1246 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

24/50 completed - 1100011026.avi

W0000 00:00:1791301881.451329    1255 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301881.458369    1257 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301881.476418    1257 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

25/50 completed - 1100011027.avi

W0000 00:00:1791301882.409571    1268 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301882.416354    1271 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301882.431644    1272 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

26/50 completed - 1100011028.avi

W0000 00:00:1791301883.376975    1281 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301883.383621    1283 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301883.404042    1283 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

27/50 completed - 1100011029.avi

W0000 00:00:1791301884.345308    1294 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301884.352433    1296 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301884.368408    1299 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

28/50 completed - 1100011031.avi

W0000 00:00:1791301885.305451    1307 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301885.312339    1309 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301885.327969    1311 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

29/50 completed - 1100011032.avi

W0000 00:00:1791301886.284505    1320 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301886.291489    1323 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301886.306892    1323 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

30/50 completed - 1100011034.avi

W0000 00:00:1791301887.281602    1333 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301887.288489    1335 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301887.304040    1335 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

31/50 completed - 1100011035.avi

W0000 00:00:1791301888.255123    1346 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301888.262011    1348 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301888.277533    1350 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

32/50 completed - 1100011037.avi

W0000 00:00:1791301889.246501    1359 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301889.253674    1362 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301889.269081    1363 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

33/50 completed - 1100011038.avi

W0000 00:00:1791301890.287232    1372 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301890.294170    1374 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301890.309629    1376 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

34/50 completed - 1100011040.avi

W0000 00:00:1791301891.245662    1385 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301891.252547    1387 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301891.268003    1387 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

35/50 completed - 1100011046.avi

W0000 00:00:1791301892.253179    1398 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301892.259981    1400 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301892.275303    1402 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

36/50 completed - 1100011047.avi

W0000 00:00:1791301893.249604    1411 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301893.256364    1414 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301893.271538    1414 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

37/50 completed - 1100011048.avi

W0000 00:00:1791301894.214045    1424 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301894.220722    1426 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301894.235822    1428 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

38/50 completed - 1100011049.avi

W0000 00:00:1791301895.181042    1437 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301895.188110    1440 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301895.203758    1439 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

39/50 completed - 1100011050.avi

W0000 00:00:1791301896.146562    1450 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301896.153737    1452 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301896.169123    1453 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

40/50 completed - 1100011051.avi

W0000 00:00:1791301897.064814    1463 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301897.071646    1466 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301897.087061    1465 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

41/50 completed - 1100011052.avi

W0000 00:00:1791301897.979518    1476 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301897.986554    1478 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301898.002145    1480 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

42/50 completed - 1100011053.avi

W0000 00:00:1791301898.906514    1489 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301898.913232    1491 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301898.928626    1492 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

43/50 completed - 1100011054.avi

W0000 00:00:1791301899.871466    1502 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301899.878272    1504 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301899.895091    1506 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

44/50 completed - 1100011055.avi

W0000 00:00:1791301900.861315    1515 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301900.868266    1518 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301900.883785    1519 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

45/50 completed - 1100011056.avi

W0000 00:00:1791301901.821460    1528 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301901.828241    1530 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301901.844798    1530 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

46/50 completed - 1100011057.avi

W0000 00:00:1791301902.761412    1541 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301902.768287    1543 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301902.785252    1545 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

47/50 completed - 1100011058.avi

W0000 00:00:1791301903.731317    1554 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301903.738341    1557 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301903.753824    1558 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

48/50 completed - 1100011059.avi

W0000 00:00:1791301904.702068    1567 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301904.709067    1570 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301904.724230    1570 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

49/50 completed - 1100011060.avi

W0000 00:00:1791301905.619092    1580 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791301905.626019    1582 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791301905.641444    1584 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

50/50 completed - 1100011062.avi

Finished!
Shape: (50, 16)

,mean_eye_openness,std_eye_openness,mean_gaze_ratio,std_gaze_ratio,mean_pitch,mean_yaw,mean_roll,mean_abs_pitch,mean_abs_yaw,mean_abs_roll,face_visibility_ratio,processed_frames,face_detected_frames,ClipID,Confusion,confused_label
0,0.342717,0.081591,0.477917,0.016081,12.994088,3.072066,1.760801,12.994088,6.043994,5.137476,1.0,30,30,1100011002.avi,0,0
1,0.385494,0.024253,0.480765,0.011968,10.843975,8.098952,-3.844077,10.843975,8.098952,3.844077,1.0,30,30,1100011003.avi,0,0
2,0.388826,0.012245,0.488781,0.014768,10.741835,9.218025,-3.780396,10.741835,9.218025,3.852060,1.0,30,30,1100011004.avi,0,0
3,0.377390,0.011641,0.482508,0.010333,11.497001,4.178317,-0.990236,11.497001,4.637832,2.009879,1.0,30,30,1100011005.avi,0,0
4,0.337944,0.034791,0.472153,0.020184,12.387394,3.205850,3.636087,12.387394,6.481199,4.819350,1.0,30,30,1100011006.avi,0,0

In [48]:
print("Missing values:")
print(visual_sample_df.isnull().sum())

print("\nFace visibility statistics:")
print(
    visual_sample_df["face_visibility_ratio"].describe()
)

print("\nLowest visibility clips:")
print(
    visual_sample_df[
        ["ClipID", "face_visibility_ratio",
         "processed_frames", "face_detected_frames"]
    ]
    .sort_values("face_visibility_ratio")
    .head(10)
)

Missing values:
mean_eye_openness        0
std_eye_openness         0
mean_gaze_ratio          0
std_gaze_ratio           0
mean_pitch               0
mean_yaw                 0
mean_roll                0
mean_abs_pitch           0
mean_abs_yaw             0
mean_abs_roll            0
face_visibility_ratio    0
processed_frames         0
face_detected_frames     0
ClipID                   0
Confusion                0
confused_label           0
dtype: int64

Face visibility statistics:
count    50.0
mean      1.0
std       0.0
min       1.0
25%       1.0
50%       1.0
75%       1.0
max       1.0
Name: face_visibility_ratio, dtype: float64

Lowest visibility clips:
           ClipID  face_visibility_ratio  processed_frames  \
0  1100011002.avi                    1.0                30
1  1100011003.avi                    1.0                30
2  1100011004.avi                    1.0                30
3  1100011005.avi                    1.0                30
4  1100011006.avi                    1.0                30
5  1100011007.avi                    1.0                30
6  1100011008.avi                    1.0                30
7  1100011009.avi                    1.0                30
8  1100011010.avi                    1.0                30
9  1100011011.avi                    1.0                30

   face_detected_frames
0                    30
1                    30
2                    30
3                    30
4                    30
5                    30
6                    30
7                    30
8                    30
9                    30

In [49]:
feature_cols = [
    "mean_eye_openness",
    "std_eye_openness",
    "mean_gaze_ratio",
    "std_gaze_ratio",
    "mean_pitch",
    "mean_yaw",
    "mean_roll",
    "mean_abs_pitch",
    "mean_abs_yaw",
    "mean_abs_roll",
    "face_visibility_ratio"
]

visual_sample_df[feature_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
mean_eye_openness,50.0,0.363781,0.011885,0.337944,0.356816,0.361860,0.371369,0.388826
std_eye_openness,50.0,0.021654,0.017719,0.006665,0.011899,0.013818,0.019742,0.081591
mean_gaze_ratio,50.0,0.468024,0.010720,0.442784,0.462926,0.470291,0.476056,0.488781
std_gaze_ratio,50.0,0.017351,0.004476,0.009138,0.014033,0.016439,0.020052,0.028587
mean_pitch,50.0,12.349643,1.190590,9.939410,11.525153,12.374212,13.458403,14.464987
mean_yaw,50.0,-7.672571,5.662543,-14.703357,-12.048281,-8.971747,-5.425920,9.218025
mean_roll,50.0,6.393369,3.677585,-3.844077,4.442986,6.491476,9.504718,12.430509
mean_abs_pitch,50.0,12.349643,1.190590,9.939410,11.525153,12.374212,13.458403,14.464987
mean_abs_yaw,50.0,9.180198,3.314280,1.472390,6.378122,9.385188,12.048281,14.703357
mean_abs_roll,50.0,6.994994,2.714653,2.009879,4.645568,6.533331,9.504718,12.430509
face_visibility_ratio,50.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [50]:
# Random 50 clips across the training dataset
random_labels = train_labels.sample(
    n=50,
    random_state=42
).reset_index(drop=True)

random_feature_rows = []

for i, row in random_labels.iterrows():

    clip_id = row["ClipID"]

    try:
        video_path = video_lookup[clip_id]

        features = extract_clip_features(
            video_path,
            samples=30
        )

        if features is None:
            print(f"FAILED - {clip_id}")
            continue

        features["ClipID"] = clip_id
        features["Confusion"] = row["Confusion"]
        features["confused_label"] = row["confused_label"]

        random_feature_rows.append(features)

        print(
            f"{len(random_feature_rows)}/50 completed - {clip_id}"
        )

    except Exception as e:
        print(f"ERROR - {clip_id}: {e}")


random_visual_df = pd.DataFrame(
    random_feature_rows
)

print("\nShape:", random_visual_df.shape)

print("\nMissing values:")
print(
    random_visual_df.isnull().sum()
)

print("\nFace visibility:")
print(
    random_visual_df[
        "face_visibility_ratio"
    ].describe()
)

print("\nLowest visibility clips:")
print(
    random_visual_df[
        [
            "ClipID",
            "face_visibility_ratio",
            "face_detected_frames"
        ]
    ]
    .sort_values("face_visibility_ratio")
    .head(10)
)

W0000 00:00:1791303223.516449    1609 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303223.523721    1612 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303223.540968    1613 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

1/50 completed - 3100771066.avi

W0000 00:00:1791303224.503669    1622 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303224.510732    1624 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303224.526596    1626 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

2/50 completed - 2100522004.avi

W0000 00:00:1791303225.493745    1635 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303225.500999    1637 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303225.516604    1639 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

3/50 completed - 1100071049.avi

W0000 00:00:1791303226.554072    1648 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303226.560954    1650 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303226.580593    1652 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

4/50 completed - 2000501041.avi

W0000 00:00:1791303227.547939    1661 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303227.554629    1664 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303227.570062    1663 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

5/50 completed - 3100682030.avi

W0000 00:00:1791303228.546270    1674 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303228.554321    1676 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303228.570998    1676 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

6/50 completed - 1100011040.avi

W0000 00:00:1791303229.541185    1687 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303229.548131    1689 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303229.565124    1690 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

7/50 completed - 1100061019.avi

W0000 00:00:1791303230.626147    1700 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303230.633125    1702 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303230.648380    1702 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

8/50 completed - 3422270169.avi

W0000 00:00:1791303231.568007    1713 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303231.575168    1716 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303231.594897    1717 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

9/50 completed - 2100592029.avi

W0000 00:00:1791303232.542543    1726 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303232.549571    1728 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303232.565833    1730 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

10/50 completed - 4000181014.avi

W0000 00:00:1791303233.536168    1739 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303233.543332    1742 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303233.558788    1743 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

11/50 completed - 3100791063.avi

W0000 00:00:1791303234.526344    1752 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303234.533274    1754 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303234.548679    1755 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

12/50 completed - 3100682007.avi

W0000 00:00:1791303235.532827    1765 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303235.539848    1767 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303235.555435    1768 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

13/50 completed - 4018350269.mp4

W0000 00:00:1791303236.743445    1778 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303236.750638    1780 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303236.766381    1782 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

14/50 completed - 3100822058.avi

W0000 00:00:1791303237.686525    1791 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303237.693821    1794 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303237.709568    1793 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

15/50 completed - 1813740149.avi

W0000 00:00:1791303238.707735    1804 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303238.714794    1806 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303238.732931    1806 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

16/50 completed - 1100171076.avi

W0000 00:00:1791303239.675028    1817 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303239.682242    1820 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303239.698097    1819 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

17/50 completed - 2100522070.avi

W0000 00:00:1791303240.726155    1830 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303240.733187    1833 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303240.752901    1834 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

18/50 completed - 3100621013.avi

W0000 00:00:1791303241.749530    1843 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303241.756631    1846 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303241.772322    1847 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

19/50 completed - 2100612006.avi

W0000 00:00:1791303243.003366    1856 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303243.010366    1858 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303243.025693    1858 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

20/50 completed - 29042801370.mp4

W0000 00:00:1791303248.479815    1869 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303248.486583    1871 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303248.503492    1872 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

21/50 completed - 1100151056.avi

W0000 00:00:1791303249.491638    1882 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303249.498624    1884 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303249.514362    1884 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

22/50 completed - 3422270135.avi

W0000 00:00:1791303250.450483    1895 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303250.457446    1897 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303250.472853    1899 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

23/50 completed - 2100521075.avi

W0000 00:00:1791303251.431166    1908 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303251.438831    1911 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303251.454228    1912 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

24/50 completed - 2000541069.avi

W0000 00:00:1791303252.447559    1921 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303252.454313    1924 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303252.469546    1924 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

25/50 completed - 3100681046.avi

W0000 00:00:1791303254.052905    1934 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303254.059880    1936 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303254.075643    1938 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

26/50 completed - 3100761042.avi

W0000 00:00:1791303255.601882    1947 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303255.608824    1950 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303255.624525    1949 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

27/50 completed - 2100581014.avi

W0000 00:00:1791303257.135751    1960 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303257.143296    1962 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303257.158817    1963 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

28/50 completed - 2100591030.avi

W0000 00:00:1791303258.680190    1973 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303258.687268    1976 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303258.702789    1976 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

29/50 completed - 2100522064.avi

W0000 00:00:1791303260.280479    1986 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303260.287593    1988 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303260.303422    1990 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

30/50 completed - 3100772037.avi

W0000 00:00:1791303262.826967    1999 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303262.834109    2001 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303262.849427    2003 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

31/50 completed - 1100142010.avi

W0000 00:00:1791303264.424114    2012 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303264.430903    2015 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303264.446249    2016 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

32/50 completed - 29042802140.mp4

W0000 00:00:1791303270.428369    2025 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303270.435249    2028 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303270.450762    2029 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

33/50 completed - 3100821033.avi

W0000 00:00:1791303272.004297    2038 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303272.011130    2040 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303272.026597    2042 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

34/50 completed - 3100742062.avi

W0000 00:00:1791303273.017691    2051 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303273.024563    2054 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303273.039723    2055 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

35/50 completed - 4000182036.avi

W0000 00:00:1791303274.012303    2064 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303274.019273    2067 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303274.035682    2067 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

36/50 completed - 202614029.mp4

W0000 00:00:1791303275.241876    2077 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303275.248960    2080 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303275.264693    2081 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

37/50 completed - 2100532020.avi

W0000 00:00:1791303276.202540    2090 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303276.209696    2093 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303276.226344    2093 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

38/50 completed - 1100051053.avi

W0000 00:00:1791303277.215508    2103 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303277.222499    2105 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303277.237505    2105 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

39/50 completed - 2056010214.avi

W0000 00:00:1791303278.190862    2116 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303278.198067    2118 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303278.213508    2120 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

40/50 completed - 1813740171.avi

W0000 00:00:1791303279.188389    2129 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303279.195664    2132 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303279.210922    2133 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

41/50 completed - 3100782065.avi

W0000 00:00:1791303280.203044    2142 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303280.209986    2144 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303280.225448    2144 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

42/50 completed - 2026140279.mp4

W0000 00:00:1791303281.388283    2155 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303281.396258    2157 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303281.411932    2159 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

43/50 completed - 3503610124.avi

W0000 00:00:1791303282.368956    2168 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303282.375696    2170 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303282.391503    2172 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

44/50 completed - 2100582020.avi

W0000 00:00:1791303283.346054    2181 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303283.353311    2183 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303283.368923    2184 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

45/50 completed - 3100761016.avi

W0000 00:00:1791303284.342035    2194 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303284.348987    2196 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303284.364454    2196 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

46/50 completed - 1100011010.avi

W0000 00:00:1791303285.363417    2207 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303285.370234    2209 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303285.385540    2211 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

47/50 completed - 29042801450.mp4

W0000 00:00:1791303290.875662    2220 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303290.882562    2223 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303290.897871    2223 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

48/50 completed - 33702102350.mp4

W0000 00:00:1791303296.336632    2233 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303296.343684    2235 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303296.359237    2235 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

49/50 completed - 240846024.avi

W0000 00:00:1791303297.304866    2246 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791303297.311753    2249 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791303297.326730    2249 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

50/50 completed - 1100071069.avi

Shape: (50, 16)

Missing values:
mean_eye_openness        0
std_eye_openness         0
mean_gaze_ratio          0
std_gaze_ratio           0
mean_pitch               0
mean_yaw                 0
mean_roll                0
mean_abs_pitch           0
mean_abs_yaw             0
mean_abs_roll            0
face_visibility_ratio    0
processed_frames         0
face_detected_frames     0
ClipID                   0
Confusion                0
confused_label           0
dtype: int64

Face visibility:
count    50.0
mean      1.0
std       0.0
min       1.0
25%       1.0
50%       1.0
75%       1.0
max       1.0
Name: face_visibility_ratio, dtype: float64

Lowest visibility clips:
           ClipID  face_visibility_ratio  face_detected_frames
0  3100771066.avi                    1.0                    30
1  2100522004.avi                    1.0                    30
2  1100071049.avi                    1.0                    30
3  2000501041.avi                    1.0                    30
4  3100682030.avi                    1.0                    30
5  1100011040.avi                    1.0                    30
6  1100061019.avi                    1.0                    30
7  3422270169.avi                    1.0                    30
8  2100592029.avi                    1.0                    30
9  4000181014.avi                    1.0                    30

In [67]:
def normalize_roll(roll):
    return ((roll + 90) % 180) - 90

In [68]:
def extract_clip_features_fast(video_path, landmarker, samples=30):

    cap = cv2.VideoCapture(video_path)

    total_frames = int(
        cap.get(cv2.CAP_PROP_FRAME_COUNT)
    )

    if total_frames <= 0:
        cap.release()
        return None

    frame_indices = np.linspace(
        0,
        total_frames - 1,
        samples
    ).astype(int)

    eye_values = []
    gaze_values = []

    pitch_values = []
    yaw_values = []
    roll_values = []

    processed_frames = 0
    face_detected_frames = 0

    for frame_index in frame_indices:

        cap.set(
            cv2.CAP_PROP_POS_FRAMES,
            int(frame_index)
        )

        success, frame = cap.read()

        if not success:
            continue

        processed_frames += 1

        rgb = cv2.cvtColor(
            frame,
            cv2.COLOR_BGR2RGB
        )

        mp_image = mp.Image(
            image_format=mp.ImageFormat.SRGB,
            data=rgb
        )

        result_frame = landmarker.detect(mp_image)

        if not result_frame.face_landmarks:
            continue

        face_detected_frames += 1

        landmarks = result_frame.face_landmarks[0]

        # -----------------------
        # Eye openness
        # -----------------------

        left_eye = calculate_eye_openness(
            landmarks,
            LEFT_EYE
        )

        right_eye = calculate_eye_openness(
            landmarks,
            RIGHT_EYE
        )

        mean_eye = (
            left_eye + right_eye
        ) / 2

        eye_values.append(mean_eye)

        # -----------------------
        # Gaze
        # -----------------------

        _, _, mean_gaze = calculate_gaze_ratio(
            landmarks
        )

        gaze_values.append(mean_gaze)

        # -----------------------
        # Head pose
        # -----------------------

        pose = estimate_head_pose(
            frame,
            landmarks
        )
        
        if pose is not None:
        
            pitch, yaw, roll = pose
        
            pitch = normalize_pitch(pitch)
            roll = normalize_roll(roll)
        
            pitch_values.append(pitch)
            yaw_values.append(yaw)
            roll_values.append(roll)

    cap.release()

    if processed_frames == 0:
        return None

    face_visibility_ratio = (
        face_detected_frames /
        processed_frames
    )

    def safe_mean(values):

        arr = np.asarray(
            values,
            dtype=float
        )

        if arr.size == 0:
            return np.nan

        return float(
            np.mean(arr)
        )


    def safe_std(values):

        arr = np.asarray(
            values,
            dtype=float
        )

        if arr.size == 0:
            return np.nan

        return float(
            np.std(arr)
        )


    return {

        "mean_eye_openness":
            safe_mean(eye_values),

        "std_eye_openness":
            safe_std(eye_values),

        "mean_gaze_ratio":
            safe_mean(gaze_values),

        "std_gaze_ratio":
            safe_std(gaze_values),

        "mean_pitch":
            safe_mean(pitch_values),

        "mean_yaw":
            safe_mean(yaw_values),

        "mean_roll":
            safe_mean(roll_values),

        "mean_abs_pitch":
            safe_mean(np.abs(pitch_values)),

        "mean_abs_yaw":
            safe_mean(np.abs(yaw_values)),

        "mean_abs_roll":
            safe_mean(np.abs(roll_values)),

        "face_visibility_ratio":
            face_visibility_ratio,

        "processed_frames":
            processed_frames,

        "face_detected_frames":
            face_detected_frames
    }

In [52]:
import os
import pandas as pd
import time

checkpoint_path = (
    "/kaggle/working/"
    "daisee_train_visual_features_checkpoint.csv"
)

final_path = (
    "/kaggle/working/"
    "daisee_train_visual_features.csv"
)

# ---------------------------------
# Create / load existing checkpoint
# ---------------------------------

if os.path.exists(checkpoint_path):

    saved_df = pd.read_csv(checkpoint_path)

    feature_rows = saved_df.to_dict(
        orient="records"
    )

    processed_clips = set(
        saved_df["ClipID"]
        .astype(str)
        .tolist()
    )

    print(
        "Checkpoint loaded:",
        len(processed_clips),
        "clips already completed"
    )

else:

    feature_rows = []
    processed_clips = set()

    print("Starting fresh.")


# ---------------------------------
# MediaPipe model - load ONCE
# ---------------------------------

options = FaceLandmarkerOptions(
    base_options=BaseOptions(
        model_asset_path=(
            "/kaggle/working/"
            "face_landmarker.task"
        )
    ),
    running_mode=VisionRunningMode.IMAGE,
    num_faces=1,
    min_face_detection_confidence=0.5,
    min_face_presence_confidence=0.5
)

start_time = time.time()


with FaceLandmarker.create_from_options(
    options
) as landmarker:

    for idx, row in train_labels.iterrows():

        clip_id = str(row["ClipID"])

        # Skip already completed clips
        if clip_id in processed_clips:
            continue

        try:

            video_path = video_lookup[
                clip_id
            ]

            features = (
                extract_clip_features_fast(
                    video_path,
                    landmarker,
                    samples=30
                )
            )

            if features is None:

                print(
                    f"FAILED - {clip_id}"
                )

                continue

            features["ClipID"] = clip_id

            features["Confusion"] = (
                row["Confusion"]
            )

            features["confused_label"] = (
                row["confused_label"]
            )

            feature_rows.append(
                features
            )

            processed_clips.add(
                clip_id
            )


            completed = len(
                feature_rows
            )


            # -------------------------
            # Save every 100 clips
            # -------------------------

            if completed % 100 == 0:

                checkpoint_df = (
                    pd.DataFrame(
                        feature_rows
                    )
                )

                checkpoint_df.to_csv(
                    checkpoint_path,
                    index=False
                )

                elapsed_minutes = (
                    time.time()
                    - start_time
                ) / 60

                print(
                    f"{completed}/"
                    f"{len(train_labels)} "
                    f"completed | "
                    f"{elapsed_minutes:.1f} min"
                )


        except Exception as e:

            print(
                f"ERROR - "
                f"{clip_id}: {e}"
            )


# ---------------------------------
# Final save
# ---------------------------------

train_visual_df = pd.DataFrame(
    feature_rows
)

train_visual_df.to_csv(
    final_path,
    index=False
)

# Save checkpoint too
train_visual_df.to_csv(
    checkpoint_path,
    index=False
)

print("\nFULL TRAIN EXTRACTION COMPLETE ✅")

print(
    "Shape:",
    train_visual_df.shape
)

print(
    "Saved:",
    final_path
)

Starting fresh.

W0000 00:00:1791304150.389321    2261 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791304150.397091    2263 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791304150.413855    2263 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

100/5358 completed | 1.5 min
200/5358 completed | 3.0 min
300/5358 completed | 4.5 min
400/5358 completed | 6.0 min
500/5358 completed | 7.5 min
600/5358 completed | 9.0 min
700/5358 completed | 10.6 min
800/5358 completed | 12.1 min
900/5358 completed | 13.6 min
1000/5358 completed | 15.1 min
1100/5358 completed | 16.7 min
1200/5358 completed | 18.2 min
1300/5358 completed | 19.6 min
1400/5358 completed | 21.1 min
1500/5358 completed | 22.9 min
1600/5358 completed | 24.3 min
1700/5358 completed | 25.8 min
1800/5358 completed | 27.3 min
1900/5358 completed | 28.7 min
2000/5358 completed | 30.2 min

[mpeg4 @ 0x215e7d00] I cbpy damaged at 16 8
[mpeg4 @ 0x215e7d00] Error at MB: 344
[mpeg4 @ 0x215e7d00] I cbpy damaged at 16 8
[mpeg4 @ 0x215e7d00] Error at MB: 344
[mpeg4 @ 0x215e7d00] I cbpy damaged at 16 8
[mpeg4 @ 0x215e7d00] Error at MB: 344

2100/5358 completed | 31.7 min
2200/5358 completed | 33.1 min
2300/5358 completed | 34.6 min
2400/5358 completed | 36.1 min
2500/5358 completed | 37.5 min
2600/5358 completed | 39.0 min
2700/5358 completed | 40.4 min
2800/5358 completed | 41.9 min
2900/5358 completed | 43.4 min
3000/5358 completed | 48.1 min
3100/5358 completed | 53.6 min
3200/5358 completed | 55.2 min
3300/5358 completed | 56.7 min
3400/5358 completed | 58.2 min
3500/5358 completed | 59.8 min
3600/5358 completed | 61.3 min
3700/5358 completed | 62.9 min
3800/5358 completed | 64.4 min
3900/5358 completed | 65.9 min
4000/5358 completed | 67.4 min
4100/5358 completed | 69.0 min
4200/5358 completed | 70.5 min
4300/5358 completed | 72.0 min
4400/5358 completed | 73.5 min
4500/5358 completed | 75.0 min
4600/5358 completed | 82.8 min
4700/5358 completed | 84.5 min
4800/5358 completed | 86.0 min
4900/5358 completed | 87.5 min
5000/5358 completed | 89.3 min
5100/5358 completed | 90.9 min
5200/5358 completed | 92.4 min
5300/5358 completed | 93.8 min

FULL TRAIN EXTRACTION COMPLETE ✅
Shape: (5358, 16)
Saved: /kaggle/working/daisee_train_visual_features.csv

In [53]:
import numpy as np

print("=== BASIC CHECK ===")

print("Shape:")
print(train_visual_df.shape)

print("\nDuplicate ClipIDs:")
print(train_visual_df["ClipID"].duplicated().sum())

print("\nMissing values:")
print(train_visual_df.isnull().sum())

numeric_cols = train_visual_df.select_dtypes(
    include=[np.number]
).columns

print("\nInfinite values:")
print(
    np.isinf(
        train_visual_df[numeric_cols]
    ).sum()
)

print("\nConfusion label counts:")
print(
    train_visual_df[
        "confused_label"
    ].value_counts()
)

print("\nConfusion label percentages:")
print(
    train_visual_df[
        "confused_label"
    ].value_counts(
        normalize=True
    ) * 100
)

=== BASIC CHECK ===
Shape:
(5358, 16)

Duplicate ClipIDs:
0

Missing values:
mean_eye_openness        0
std_eye_openness         0
mean_gaze_ratio          0
std_gaze_ratio           0
mean_pitch               0
mean_yaw                 0
mean_roll                0
mean_abs_pitch           0
mean_abs_yaw             0
mean_abs_roll            0
face_visibility_ratio    0
processed_frames         0
face_detected_frames     0
ClipID                   0
Confusion                0
confused_label           0
dtype: int64

Infinite values:
mean_eye_openness        0
std_eye_openness         0
mean_gaze_ratio          0
std_gaze_ratio           0
mean_pitch               0
mean_yaw                 0
mean_roll                0
mean_abs_pitch           0
mean_abs_yaw             0
mean_abs_roll            0
face_visibility_ratio    0
processed_frames         0
face_detected_frames     0
Confusion                0
confused_label           0
dtype: int64

Confusion label counts:
confused_label
0    3616
1    1742
Name: count, dtype: int64

Confusion label percentages:
confused_label
0    67.487869
1    32.512131
Name: proportion, dtype: float64

In [56]:
print("=== FACE VISIBILITY ===")

print(
    train_visual_df[
        "face_visibility_ratio"
    ].describe()
)

print(
    "\nClips visibility < 1.0:",
    (
        train_visual_df[
            "face_visibility_ratio"
        ] < 1.0
    ).sum()
)

print(
    "Clips visibility < 0.8:",
    (
        train_visual_df[
            "face_visibility_ratio"
        ] < 0.8
    ).sum()
)

print(
    "Clips visibility < 0.5:",
    (
        train_visual_df[
            "face_visibility_ratio"
        ] < 0.5
    ).sum()
)

=== FACE VISIBILITY ===
count    5358.000000
mean        0.999832
std         0.006487
min         0.566667
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: face_visibility_ratio, dtype: float64

Clips visibility < 1.0: 9
Clips visibility < 0.8: 1
Clips visibility < 0.5: 0

In [57]:
feature_cols = [
    "mean_eye_openness",
    "std_eye_openness",
    "mean_gaze_ratio",
    "std_gaze_ratio",
    "mean_pitch",
    "mean_yaw",
    "mean_roll",
    "mean_abs_pitch",
    "mean_abs_yaw",
    "mean_abs_roll",
    "face_visibility_ratio"
]

train_visual_df[
    feature_cols
].describe().T

,count,mean,std,min,25%,50%,75%,max
mean_eye_openness,5358.0,0.367621,0.050276,0.072161,0.338769,0.370847,0.401926,0.515344
std_eye_openness,5358.0,0.041965,0.026189,0.004154,0.019214,0.037971,0.059649,0.162739
mean_gaze_ratio,5358.0,0.494637,0.020326,0.352601,0.482110,0.495563,0.507867,0.621659
std_gaze_ratio,5358.0,0.019775,0.010658,0.002664,0.013034,0.017574,0.023961,0.138869
mean_pitch,5358.0,-4.034655,8.420801,-39.407892,-9.410149,-3.409573,1.451838,29.506118
mean_yaw,5358.0,2.086269,10.082106,-36.989513,-4.432516,2.003657,8.424086,39.685546
mean_roll,5358.0,-0.205424,16.223677,-178.096820,-4.821503,-0.872125,2.263088,179.039877
mean_abs_pitch,5358.0,7.444158,5.832247,0.187618,2.758568,6.190950,10.600923,39.407892
mean_abs_yaw,5358.0,8.455453,6.309091,0.355285,3.783605,7.124841,11.365579,39.685546
mean_abs_roll,5358.0,6.910392,16.094059,0.100392,1.897784,3.987821,6.830096,179.039877
face_visibility_ratio,5358.0,0.999832,0.006487,0.566667,1.000000,1.000000,1.000000,1.000000

In [59]:
print("Suspicious roll checks")

print(
    "abs(mean_roll) > 45:",
    (train_visual_df["mean_roll"].abs() > 45).sum()
)

print(
    "abs(mean_roll) > 90:",
    (train_visual_df["mean_roll"].abs() > 90).sum()
)

print(
    "mean_abs_roll > 45:",
    (train_visual_df["mean_abs_roll"] > 45).sum()
)

print(
    "mean_abs_roll > 90:",
    (train_visual_df["mean_abs_roll"] > 90).sum()
)

print("\nMost extreme clips:")

print(
    train_visual_df[
        [
            "ClipID",
            "mean_roll",
            "mean_abs_roll",
            "mean_pitch",
            "mean_yaw"
        ]
    ]
    .sort_values(
        "mean_abs_roll",
        ascending=False
    )
    .head(20)
)

Suspicious roll checks
abs(mean_roll) > 45: 80
abs(mean_roll) > 90: 47
mean_abs_roll > 45: 101
mean_abs_roll > 90: 53

Most extreme clips:
              ClipID   mean_roll  mean_abs_roll  mean_pitch   mean_yaw
1528  2056010218.avi  179.039877     179.039877  -25.834302  -1.172371
1529  2056010219.avi  178.966101     178.966101  -26.568568  -2.159381
1551  2056010249.avi  178.887386     178.887386  -26.383450  -2.526693
334   1100062017.avi -178.096820     178.096820  -27.357764  -2.235510
1530  2056010222.avi  178.068112     178.068112  -27.733622  -2.878956
1531  2056010224.avi  177.999501     177.999501  -29.581272  -2.585287
1532  2056010225.avi  177.653527     177.653527  -28.958147  -3.085118
328   1100062004.avi -177.293675     177.293675  -33.100470   0.682920
1539  2056010234.avi  177.044423     177.044423  -26.911935  -6.386287
1538  2056010233.avi  176.902508     176.902508  -26.708984  -6.562835
329   1100062005.avi -176.770485     176.770485  -34.283035   0.878092
346   1100062054.avi  174.541595     174.541595  -30.063015   8.223672
330   1100062007.avi -173.975938     173.975938  -31.180182  20.541681
315   1100061053.avi  173.749319     173.749319  -29.732808  18.928931
773   1100151004.avi  -29.617535     173.726648  -19.280513 -22.774816
1546  2056010241.avi  173.041527     173.041527  -24.601326 -12.274904
1553  2056010250.avi  172.686605     172.740381  -25.775070  -3.114952
1537  2056010232.avi  171.093045     171.174183  -24.573989  -4.622768
305   1100061040.avi  170.779493     171.066327  -39.407892   9.199140
794   1100151033.avi  170.160849     170.422480  -25.096534  -4.999353

In [64]:
def normalize_roll(roll):
    """
    Convert roll angle to equivalent range [-90, 90).
    
    Examples:
      179  -> -1
     -178  ->  2
      170  -> -10
      -175 ->  5
    """
    return ((roll + 90) % 180) - 90

In [65]:
test_angles = [
    179.039877,
    -178.096820,
    170.779493,
    -173.975938,
    12.4,
    -8.5
]

for a in test_angles:
    print(
        a,
        "->",
        round(normalize_roll(a), 2)
    )

179.039877 -> -0.96
-178.09682 -> 1.9
170.779493 -> -9.22
-173.975938 -> 6.02
12.4 -> 12.4
-8.5 -> -8.5

In [69]:
test_clip = "2056010218.avi"
test_path = video_lookup[test_clip]

options = FaceLandmarkerOptions(
    base_options=BaseOptions(
        model_asset_path="/kaggle/working/face_landmarker.task"
    ),
    running_mode=VisionRunningMode.IMAGE,
    num_faces=1,
    min_face_detection_confidence=0.5,
    min_face_presence_confidence=0.5
)

with FaceLandmarker.create_from_options(options) as landmarker:

    corrected_features = extract_clip_features_fast(
        test_path,
        landmarker,
        samples=30
    )

print("Corrected mean_roll:",
      round(corrected_features["mean_roll"], 4))

print("Corrected mean_abs_roll:",
      round(corrected_features["mean_abs_roll"], 4))

print("\nFull features:")
corrected_features

W0000 00:00:1791311499.771118   39815 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791311499.816945   39817 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791311499.852050   39819 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

Corrected mean_roll: -0.9601
Corrected mean_abs_roll: 0.9601

Full features:

{'mean_eye_openness': 0.4238797609035148,
 'std_eye_openness': 0.017281514592464877,
 'mean_gaze_ratio': 0.49963306490213816,
 'std_gaze_ratio': 0.043818725878877404,
 'mean_pitch': -25.834301667372948,
 'mean_yaw': -1.1723711512972137,
 'mean_roll': -0.9601226566937195,
 'mean_abs_pitch': 25.834301667372948,
 'mean_abs_yaw': 1.2712770250313927,
 'mean_abs_roll': 0.9601226566937195,
 'face_visibility_ratio': 1.0,
 'processed_frames': 30,
 'face_detected_frames': 30}

In [70]:
import os
import pandas as pd
import time

# NEW filenames - important
checkpoint_path_v2 = (
    "/kaggle/working/"
    "daisee_train_visual_features_rollfix_checkpoint.csv"
)

final_path_v2 = (
    "/kaggle/working/"
    "daisee_train_visual_features_rollfix.csv"
)

# ------------------------------------------------
# Load corrected checkpoint if run was interrupted
# ------------------------------------------------

if os.path.exists(checkpoint_path_v2):

    saved_df = pd.read_csv(checkpoint_path_v2)

    feature_rows = saved_df.to_dict(
        orient="records"
    )

    processed_clips = set(
        saved_df["ClipID"]
        .astype(str)
        .tolist()
    )

    print(
        "Corrected checkpoint loaded:",
        len(processed_clips),
        "clips already completed"
    )

else:

    feature_rows = []
    processed_clips = set()

    print("Starting corrected extraction from fresh.")


# ------------------------------------------------
# Load MediaPipe FaceLandmarker ONCE
# ------------------------------------------------

options = FaceLandmarkerOptions(
    base_options=BaseOptions(
        model_asset_path="/kaggle/working/face_landmarker.task"
    ),
    running_mode=VisionRunningMode.IMAGE,
    num_faces=1,
    min_face_detection_confidence=0.5,
    min_face_presence_confidence=0.5
)

start_time = time.time()


with FaceLandmarker.create_from_options(options) as landmarker:

    for idx, row in train_labels.iterrows():

        clip_id = str(row["ClipID"])

        if clip_id in processed_clips:
            continue

        try:

            video_path = video_lookup[clip_id]

            # IMPORTANT:
            # This is the UPDATED function containing:
            # roll = normalize_roll(roll)
            features = extract_clip_features_fast(
                video_path,
                landmarker,
                samples=30
            )

            if features is None:
                print(f"FAILED - {clip_id}")
                continue

            features["ClipID"] = clip_id
            features["Confusion"] = row["Confusion"]
            features["confused_label"] = row["confused_label"]

            feature_rows.append(features)
            processed_clips.add(clip_id)

            completed = len(feature_rows)

            # Save every 100 clips
            if completed % 100 == 0:

                checkpoint_df = pd.DataFrame(
                    feature_rows
                )

                checkpoint_df.to_csv(
                    checkpoint_path_v2,
                    index=False
                )

                elapsed_minutes = (
                    time.time() - start_time
                ) / 60

                print(
                    f"{completed}/{len(train_labels)} "
                    f"completed | "
                    f"{elapsed_minutes:.1f} min"
                )

        except Exception as e:

            print(
                f"ERROR - {clip_id}: {e}"
            )


# ------------------------------------------------
# Final corrected save
# ------------------------------------------------

train_visual_df_v2 = pd.DataFrame(
    feature_rows
)

train_visual_df_v2.to_csv(
    final_path_v2,
    index=False
)

train_visual_df_v2.to_csv(
    checkpoint_path_v2,
    index=False
)

print("\nCORRECTED TRAIN EXTRACTION COMPLETE ✅")
print("Shape:", train_visual_df_v2.shape)
print("Saved:", final_path_v2)

Starting corrected extraction from fresh.

W0000 00:00:1791311597.080563   39830 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791311597.092025   39832 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791311597.119408   39834 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

100/5358 completed | 1.5 min
200/5358 completed | 3.0 min
300/5358 completed | 4.6 min
400/5358 completed | 6.1 min
500/5358 completed | 7.6 min
600/5358 completed | 9.2 min
700/5358 completed | 10.8 min
800/5358 completed | 12.3 min
900/5358 completed | 13.8 min
1000/5358 completed | 15.4 min
1100/5358 completed | 16.9 min
1200/5358 completed | 18.4 min
1300/5358 completed | 19.9 min
1400/5358 completed | 21.4 min
1500/5358 completed | 23.2 min
1600/5358 completed | 24.7 min
1700/5358 completed | 26.2 min
1800/5358 completed | 27.6 min
1900/5358 completed | 29.1 min
2000/5358 completed | 30.6 min

[mpeg4 @ 0x216fe4c0] I cbpy damaged at 16 8
[mpeg4 @ 0x216fe4c0] Error at MB: 344
[mpeg4 @ 0x216fe4c0] I cbpy damaged at 16 8
[mpeg4 @ 0x216fe4c0] Error at MB: 344
[mpeg4 @ 0x216fe4c0] I cbpy damaged at 16 8
[mpeg4 @ 0x216fe4c0] Error at MB: 344

2100/5358 completed | 32.1 min
2200/5358 completed | 33.6 min
2300/5358 completed | 35.0 min
2400/5358 completed | 36.6 min
2500/5358 completed | 38.0 min
2600/5358 completed | 39.5 min
2700/5358 completed | 41.0 min
2800/5358 completed | 42.5 min
2900/5358 completed | 44.0 min
3000/5358 completed | 48.7 min
3100/5358 completed | 54.2 min
3200/5358 completed | 55.8 min
3300/5358 completed | 57.4 min
3400/5358 completed | 58.9 min
3500/5358 completed | 60.4 min
3600/5358 completed | 61.9 min
3700/5358 completed | 63.4 min
3800/5358 completed | 64.9 min
3900/5358 completed | 66.5 min
4000/5358 completed | 68.0 min
4100/5358 completed | 69.6 min
4200/5358 completed | 71.1 min
4300/5358 completed | 72.6 min
4400/5358 completed | 74.1 min
4500/5358 completed | 75.6 min
4600/5358 completed | 83.4 min
4700/5358 completed | 85.2 min
4800/5358 completed | 86.7 min
4900/5358 completed | 88.2 min
5000/5358 completed | 89.9 min
5100/5358 completed | 91.5 min
5200/5358 completed | 93.1 min
5300/5358 completed | 94.5 min

CORRECTED TRAIN EXTRACTION COMPLETE ✅
Shape: (5358, 16)
Saved: /kaggle/working/daisee_train_visual_features_rollfix.csv

In [71]:
print("=== CORRECTED ROLL CHECK ===")

print(
    "abs(mean_roll) > 45:",
    (train_visual_df_v2["mean_roll"].abs() > 45).sum()
)

print(
    "abs(mean_roll) > 90:",
    (train_visual_df_v2["mean_roll"].abs() > 90).sum()
)

print(
    "mean_abs_roll > 45:",
    (train_visual_df_v2["mean_abs_roll"] > 45).sum()
)

print(
    "mean_abs_roll > 90:",
    (train_visual_df_v2["mean_abs_roll"] > 90).sum()
)

print("\nRoll statistics:")

print(
    train_visual_df_v2[
        ["mean_roll", "mean_abs_roll"]
    ].describe()
)

print("\nMost extreme corrected clips:")

print(
    train_visual_df_v2[
        [
            "ClipID",
            "mean_roll",
            "mean_abs_roll",
            "mean_pitch",
            "mean_yaw"
        ]
    ]
    .sort_values(
        "mean_abs_roll",
        ascending=False
    )
    .head(15)
)

=== CORRECTED ROLL CHECK ===
abs(mean_roll) > 45: 5
abs(mean_roll) > 90: 0
mean_abs_roll > 45: 5
mean_abs_roll > 90: 0

Roll statistics:
         mean_roll  mean_abs_roll
count  5358.000000    5358.000000
mean     -1.283696       4.576772
std       5.656700       3.841020
min     -66.120550       0.100392
25%      -4.870164       1.851679
50%      -1.013678       3.820074
75%       2.032367       6.368724
max      34.564058      66.120550

Most extreme corrected clips:
               ClipID  mean_roll  mean_abs_roll  mean_pitch   mean_yaw
3068    303830139.mp4 -66.120550      66.120550  -13.086559   5.652934
3067    303830138.mp4 -65.167761      65.167761  -14.189597   7.126845
3071    303830143.mp4 -60.711960      60.711960  -15.261504   6.075449
3070    303830141.mp4 -59.746843      59.746843  -15.744520   5.121142
3072    303830144.mp4 -50.473822      50.473822  -11.302464   0.994829
3112     30383023.mp4 -22.866048      35.070748    3.872149 -10.296039
3127    303830259.mp4  34.564058      34.813735   -0.469594  11.484271
2889    248510127.mp4  33.073515      33.073515   -2.100923  -2.999354
3123     30383025.mp4  27.382491      27.382491   -4.650117   9.131915
3083    303830159.mp4 -22.936805      22.936805    4.966969   3.973650
2998  29042801790.mp4  10.661333      22.321528    0.159563  -8.839401
3073    303830146.mp4 -21.174753      21.174753  -10.299250  12.524758
3074    303830147.mp4 -21.158174      21.158174  -10.683303  13.385409
2876    240846028.avi -19.754185      19.754185    6.236565  15.821399
2826   2408460163.avi  -9.145829      19.354523    2.907829  19.386592

In [72]:
import cv2
import matplotlib.pyplot as plt

clips_to_check = [
    "303830139.mp4",
    "303830138.mp4",
    "303830143.mp4",
    "303830141.mp4",
    "303830144.mp4"
]

for clip_id in clips_to_check:

    path = video_lookup[clip_id]

    cap = cv2.VideoCapture(path)

    frame_count = int(
        cap.get(cv2.CAP_PROP_FRAME_COUNT)
    )

    cap.set(
        cv2.CAP_PROP_POS_FRAMES,
        frame_count // 2
    )

    success, frame = cap.read()

    cap.release()

    if not success:
        print("Could not read:", clip_id)
        continue

    rgb = cv2.cvtColor(
        frame,
        cv2.COLOR_BGR2RGB
    )

    roll_value = train_visual_df_v2.loc[
        train_visual_df_v2["ClipID"] == clip_id,
        "mean_roll"
    ].iloc[0]

    plt.figure(figsize=(6, 4))

    plt.imshow(rgb)

    plt.title(
        f"{clip_id} | mean roll = {roll_value:.2f}°"
    )

    plt.axis("off")
    plt.show()

In [73]:
val_label_path = (
    "/kaggle/input/datasets/rasangabawanthi/"
    "mindbridge-daisee/DAiSEE/Labels/ValidationLabels.csv"
)

test_label_path = (
    "/kaggle/input/datasets/rasangabawanthi/"
    "mindbridge-daisee/DAiSEE/Labels/TestLabels.csv"
)

val_labels = pd.read_csv(val_label_path)
test_labels = pd.read_csv(test_label_path)

# Clean column names
val_labels.columns = val_labels.columns.str.strip()
test_labels.columns = test_labels.columns.str.strip()

# Binary confusion labels
val_labels["confused_label"] = (
    val_labels["Confusion"] >= 1
).astype(int)

test_labels["confused_label"] = (
    test_labels["Confusion"] >= 1
).astype(int)

print("Validation shape:", val_labels.shape)
print("Test shape:", test_labels.shape)

print("\nValidation confusion:")
print(val_labels["confused_label"].value_counts())

print("\nTest confusion:")
print(test_labels["confused_label"].value_counts())

Validation shape: (1429, 6)
Test shape: (1784, 6)

Validation confusion:
confused_label
0    942
1    487
Name: count, dtype: int64

Test confusion:
confused_label
0    1200
1     584
Name: count, dtype: int64

In [74]:
def process_daisee_split(
    labels_df,
    split_name,
    samples=30
):

    checkpoint_path = (
        f"/kaggle/working/"
        f"daisee_{split_name}_visual_features_checkpoint.csv"
    )

    final_path = (
        f"/kaggle/working/"
        f"daisee_{split_name}_visual_features.csv"
    )

    if os.path.exists(checkpoint_path):

        saved_df = pd.read_csv(checkpoint_path)

        rows = saved_df.to_dict(
            orient="records"
        )

        completed_ids = set(
            saved_df["ClipID"]
            .astype(str)
            .tolist()
        )

        print(
            f"{split_name}: checkpoint loaded -",
            len(completed_ids)
        )

    else:

        rows = []
        completed_ids = set()

        print(
            f"{split_name}: starting fresh"
        )

    options = FaceLandmarkerOptions(
        base_options=BaseOptions(
            model_asset_path=(
                "/kaggle/working/"
                "face_landmarker.task"
            )
        ),
        running_mode=VisionRunningMode.IMAGE,
        num_faces=1,
        min_face_detection_confidence=0.5,
        min_face_presence_confidence=0.5
    )

    start_time = time.time()

    with FaceLandmarker.create_from_options(
        options
    ) as landmarker:

        for _, row in labels_df.iterrows():

            clip_id = str(
                row["ClipID"]
            )

            if clip_id in completed_ids:
                continue

            try:

                video_path = video_lookup[
                    clip_id
                ]

                features = (
                    extract_clip_features_fast(
                        video_path,
                        landmarker,
                        samples=samples
                    )
                )

                if features is None:
                    print(
                        "FAILED -",
                        clip_id
                    )
                    continue

                features["ClipID"] = clip_id
                features["Confusion"] = row["Confusion"]

                features["confused_label"] = (
                    row["confused_label"]
                )

                rows.append(features)
                completed_ids.add(clip_id)

                completed = len(rows)

                if completed % 100 == 0:

                    pd.DataFrame(
                        rows
                    ).to_csv(
                        checkpoint_path,
                        index=False
                    )

                    mins = (
                        time.time()
                        - start_time
                    ) / 60

                    print(
                        f"{completed}/"
                        f"{len(labels_df)} "
                        f"completed | "
                        f"{mins:.1f} min"
                    )

            except Exception as e:

                print(
                    f"ERROR - {clip_id}: {e}"
                )

    result_df = pd.DataFrame(
        rows
    )

    result_df.to_csv(
        final_path,
        index=False
    )

    result_df.to_csv(
        checkpoint_path,
        index=False
    )

    print(
        f"\n{split_name.upper()} COMPLETE ✅"
    )

    print(
        "Shape:",
        result_df.shape
    )

    print(
        "Saved:",
        final_path
    )

    return result_df

In [75]:
val_visual_df = process_daisee_split(
    val_labels,
    "validation",
    samples=30
)

validation: starting fresh

W0000 00:00:1791317900.601723   77392 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791317900.633950   77394 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791317900.683721   77395 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

100/1429 completed | 1.5 min
200/1429 completed | 3.0 min
300/1429 completed | 4.4 min
400/1429 completed | 6.0 min
500/1429 completed | 7.4 min
600/1429 completed | 9.0 min
700/1429 completed | 10.5 min
800/1429 completed | 12.0 min
900/1429 completed | 13.5 min
1000/1429 completed | 15.0 min
1100/1429 completed | 16.7 min
1200/1429 completed | 18.1 min
1300/1429 completed | 19.7 min
1400/1429 completed | 21.2 min

VALIDATION COMPLETE ✅
Shape: (1429, 16)
Saved: /kaggle/working/daisee_validation_visual_features.csv

In [76]:
test_visual_df = process_daisee_split(
    test_labels,
    "test",
    samples=30
)

test: starting fresh

W0000 00:00:1791319267.139045   87406 face_landmarker_graph.cc:180] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
W0000 00:00:1791319267.151632   87409 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1791319267.196581   87411 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

100/1784 completed | 1.5 min
200/1784 completed | 2.9 min
300/1784 completed | 4.4 min
400/1784 completed | 5.9 min
500/1784 completed | 7.4 min
600/1784 completed | 8.9 min
700/1784 completed | 10.4 min
800/1784 completed | 11.8 min
900/1784 completed | 13.3 min
1000/1784 completed | 14.8 min
1100/1784 completed | 16.3 min
1200/1784 completed | 17.8 min
1300/1784 completed | 19.3 min
1400/1784 completed | 21.8 min
1500/1784 completed | 30.3 min
1600/1784 completed | 34.0 min
1700/1784 completed | 35.6 min

TEST COMPLETE ✅
Shape: (1784, 16)
Saved: /kaggle/working/daisee_test_visual_features.csv

In [77]:
print("=== DATASET SHAPES ===")
print("Train:", train_visual_df_v2.shape)
print("Validation:", val_visual_df.shape)
print("Test:", test_visual_df.shape)

print("\n=== MISSING VALUES ===")
print("Train:", train_visual_df_v2.isnull().sum().sum())
print("Validation:", val_visual_df.isnull().sum().sum())
print("Test:", test_visual_df.isnull().sum().sum())

print("\n=== LABEL DISTRIBUTION ===")

print("\nTrain:")
print(train_visual_df_v2["confused_label"].value_counts())

print("\nValidation:")
print(val_visual_df["confused_label"].value_counts())

print("\nTest:")
print(test_visual_df["confused_label"].value_counts())

print("\n=== ROLL RANGE CHECK ===")

for name, df in [
    ("Train", train_visual_df_v2),
    ("Validation", val_visual_df),
    ("Test", test_visual_df)
]:
    print(
        name,
        "mean_roll range:",
        round(df["mean_roll"].min(), 2),
        "to",
        round(df["mean_roll"].max(), 2)
    )

=== DATASET SHAPES ===
Train: (5358, 16)
Validation: (1429, 16)
Test: (1784, 16)

=== MISSING VALUES ===
Train: 0
Validation: 0
Test: 0

=== LABEL DISTRIBUTION ===

Train:
confused_label
0    3616
1    1742
Name: count, dtype: int64

Validation:
confused_label
0    942
1    487
Name: count, dtype: int64

Test:
confused_label
0    1200
1     584
Name: count, dtype: int64

=== ROLL RANGE CHECK ===
Train mean_roll range: -66.12 to 34.56
Validation mean_roll range: -19.34 to 18.96
Test mean_roll range: -35.1 to 31.98

In [78]:
visual_features = [
    "mean_eye_openness",
    "std_eye_openness",
    "mean_gaze_ratio",
    "std_gaze_ratio",
    "mean_pitch",
    "mean_yaw",
    "mean_roll",
    "mean_abs_pitch",
    "mean_abs_yaw",
    "mean_abs_roll",
    "face_visibility_ratio"
]

X_train_visual = train_visual_df_v2[visual_features]
y_train_visual = train_visual_df_v2["confused_label"]

X_val_visual = val_visual_df[visual_features]
y_val_visual = val_visual_df["confused_label"]

X_test_visual = test_visual_df[visual_features]
y_test_visual = test_visual_df["confused_label"]

negative_count = (y_train_visual == 0).sum()
positive_count = (y_train_visual == 1).sum()

scale_pos_weight = negative_count / positive_count

print("Train shape:", X_train_visual.shape)
print("Validation shape:", X_val_visual.shape)
print("Test shape:", X_test_visual.shape)

print("Negative:", negative_count)
print("Positive:", positive_count)
print("scale_pos_weight:", round(scale_pos_weight, 4))

Train shape: (5358, 11)
Validation shape: (1429, 11)
Test shape: (1784, 11)
Negative: 3616
Positive: 1742
scale_pos_weight: 2.0758

In [79]:
from xgboost import XGBClassifier

visual_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.03,

    subsample=0.8,
    colsample_bytree=0.8,

    min_child_weight=3,

    scale_pos_weight=scale_pos_weight,

    objective="binary:logistic",
    eval_metric="aucpr",

    tree_method="hist",

    random_state=42,
    n_jobs=-1
)

visual_model.fit(
    X_train_visual,
    y_train_visual
)

print("Visual Model A training complete ✅")

Visual Model A training complete ✅

In [80]:
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    classification_report,
    confusion_matrix
)

val_prob = visual_model.predict_proba(
    X_val_visual
)[:, 1]

val_pred_05 = (
    val_prob >= 0.5
).astype(int)

print(
    "Validation ROC-AUC:",
    round(
        roc_auc_score(
            y_val_visual,
            val_prob
        ),
        4
    )
)

print(
    "Validation PR-AUC:",
    round(
        average_precision_score(
            y_val_visual,
            val_prob
        ),
        4
    )
)

print("\nClassification Report @ threshold 0.50:")
print(
    classification_report(
        y_val_visual,
        val_pred_05,
        digits=4
    )
)

print("Confusion Matrix:")
print(
    confusion_matrix(
        y_val_visual,
        val_pred_05
    )
)

Validation ROC-AUC: 0.5483
Validation PR-AUC: 0.3746

Classification Report @ threshold 0.50:
              precision    recall  f1-score   support

           0     0.6770    0.6008    0.6367       942
           1     0.3659    0.4456    0.4019       487

    accuracy                         0.5479      1429
   macro avg     0.5215    0.5232    0.5193      1429
weighted avg     0.5710    0.5479    0.5566      1429

Confusion Matrix:
[[566 376]
 [270 217]]

In [81]:
import numpy as np
import pandas as pd
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    confusion_matrix
)

threshold_results = []

for threshold in np.arange(0.10, 0.91, 0.02):

    pred = (
        val_prob >= threshold
    ).astype(int)

    macro_f1 = f1_score(
        y_val_visual,
        pred,
        average="macro"
    )

    confused_f1 = f1_score(
        y_val_visual,
        pred,
        pos_label=1
    )

    precision = precision_score(
        y_val_visual,
        pred,
        pos_label=1,
        zero_division=0
    )

    recall = recall_score(
        y_val_visual,
        pred,
        pos_label=1,
        zero_division=0
    )

    threshold_results.append({
        "threshold": round(threshold, 2),
        "macro_f1": macro_f1,
        "confused_f1": confused_f1,
        "precision": precision,
        "recall": recall
    })

threshold_df = pd.DataFrame(
    threshold_results
)

threshold_df = threshold_df.sort_values(
    "macro_f1",
    ascending=False
)

threshold_df.head(10)

    threshold  macro_f1  confused_f1  precision    recall
20       0.50  0.519261     0.401852   0.365936  0.445585
19       0.48  0.516486     0.426483   0.366864  0.509240
22       0.54  0.514191     0.338090   0.363208  0.316222
21       0.52  0.513474     0.366733   0.358121  0.375770
18       0.46  0.513069     0.446964   0.368984  0.566735
23       0.56  0.507683     0.304762   0.362606  0.262834
17       0.44  0.505221     0.467827   0.370504  0.634497
24       0.58  0.501100     0.269281   0.370504  0.211499
16       0.42  0.490893     0.477354   0.367257  0.681725
25       0.60  0.490153     0.230769   0.376744  0.166324

In [82]:
best_threshold = threshold_df.iloc[0]["threshold"]

best_val_pred = (
    val_prob >= best_threshold
).astype(int)

print("Best threshold:", best_threshold)

print(
    "Best Macro F1:",
    round(
        f1_score(
            y_val_visual,
            best_val_pred,
            average="macro"
        ),
        4
    )
)

print(
    "Confused precision:",
    round(
        precision_score(
            y_val_visual,
            best_val_pred,
            zero_division=0
        ),
        4
    )
)

print(
    "Confused recall:",
    round(
        recall_score(
            y_val_visual,
            best_val_pred,
            zero_division=0
        ),
        4
    )
)

print(
    "Confused F1:",
    round(
        f1_score(
            y_val_visual,
            best_val_pred
        ),
        4
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_val_visual,
        best_val_pred
    )
)

Best threshold: 0.5
Best Macro F1: 0.5193
Confused precision: 0.3659
Confused recall: 0.4456
Confused F1: 0.4019

Confusion Matrix:
[[566 376]
 [270 217]]

In [83]:
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score
)

# Frozen threshold from validation
FINAL_VISUAL_THRESHOLD = 0.50

# Test probabilities
test_prob = visual_model.predict_proba(
    X_test_visual
)[:, 1]

# Final predictions
test_pred = (
    test_prob >= FINAL_VISUAL_THRESHOLD
).astype(int)

print("=== FINAL VISUAL MODEL A - TEST RESULTS ===")

print(
    "ROC-AUC:",
    round(
        roc_auc_score(
            y_test_visual,
            test_prob
        ),
        4
    )
)

print(
    "PR-AUC:",
    round(
        average_precision_score(
            y_test_visual,
            test_prob
        ),
        4
    )
)

print(
    "Macro F1:",
    round(
        f1_score(
            y_test_visual,
            test_pred,
            average="macro"
        ),
        4
    )
)

print(
    "Confused Precision:",
    round(
        precision_score(
            y_test_visual,
            test_pred,
            zero_division=0
        ),
        4
    )
)

print(
    "Confused Recall:",
    round(
        recall_score(
            y_test_visual,
            test_pred,
            zero_division=0
        ),
        4
    )
)

print(
    "Confused F1:",
    round(
        f1_score(
            y_test_visual,
            test_pred
        ),
        4
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_test_visual,
        test_pred,
        digits=4
    )
)

print("Confusion Matrix:")
print(
    confusion_matrix(
        y_test_visual,
        test_pred
    )
)

=== FINAL VISUAL MODEL A - TEST RESULTS ===
ROC-AUC: 0.5757
PR-AUC: 0.3883
Macro F1: 0.5426
Confused Precision: 0.3832
Confused Recall: 0.5788
Confused F1: 0.4611

Classification Report:
              precision    recall  f1-score   support

           0     0.7273    0.5467    0.6242      1200
           1     0.3832    0.5788    0.4611       584

    accuracy                         0.5572      1784
   macro avg     0.5552    0.5627    0.5426      1784
weighted avg     0.6146    0.5572    0.5708      1784

Confusion Matrix:
[[656 544]
 [246 338]]

In [84]:
visual_model.save_model(
    "/kaggle/working/mindbridge_visual_model.json"
)

print("Visual model saved ✅")

Visual model saved ✅

In [85]:
import json

visual_model_info = {
    "model_name": "MindBridge Visual Model A",
    "dataset": "DAiSEE",
    "target": "confused_label",
    "target_rule": "Confusion >= 1",
    "threshold": 0.50,

    "features": visual_features,

    "test_metrics": {
        "roc_auc": 0.5757,
        "pr_auc": 0.3883,
        "macro_f1": 0.5426,
        "confused_precision": 0.3832,
        "confused_recall": 0.5788,
        "confused_f1": 0.4611
    }
}

with open(
    "/kaggle/working/visual_model_info.json",
    "w"
) as f:
    json.dump(
        visual_model_info,
        f,
        indent=4
    )

print("Visual metadata saved ✅")

Visual metadata saved ✅